#!/usr/bin/env python3
import sys


def solve(S_x: int, S_y: int, G_x: int, G_y: int):
    # 直線の方程式をもとめてy=0のときのxをだす
    S_y *= -1
    m = (S_y - G_y) / (S_x - G_x)
    n = S_y - (m * S_x)
    x = n / m
    print(x * -1)


    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S_x = int(next(tokens))  # type: int
    S_y = int(next(tokens))  # type: int
    G_x = int(next(tokens))  # type: int
    G_y = int(next(tokens))  # type: int
    solve(S_x, S_y, G_x, G_y)

if __name__ == '__main__':
    main()
