#!/usr/bin/env python3
import sys


def solve(H: int, W: int, A: "List[List[int]]"):
    m = float('inf')
    for i in range(H):
        t = min(A[i])
        m = min(t, m)
    sum = 0
    for i in range(H):
        for j in range(W):
            v = A[i][j]
            sum += v-m
    print(sum)


    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    A = [[int(next(tokens)) for _ in range(W)] for _ in range(H)]  # type: "List[List[int]]"
    solve(H, W, A)

if __name__ == '__main__':
    main()
