#!/usr/bin/env python3
import sys


def solve(B: int, C: int):
    if C == 0:
        print(1)
        return 0

    n = C // 2
    NB = B * -1
    a = NB - n
    b = NB + n
    c = B - n
    d = B
    # C が2以下の場合は元のBよりも大きくなることはない
    if C >= 2:
        d = B + (C-2)//2

    if C % 2 == 0:
        a = NB - (n - 1)
        b = NB + (n - 1)
    ans = (b - a +1) + (d -c +1) - max(0, min(b,d) - max(a, c) + 1)
    print(ans)

    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    B = int(next(tokens))  # type: int
    C = int(next(tokens))  # type: int
    solve(B, C)

if __name__ == '__main__':
    main()
