#!/usr/bin/env python3
import sys


def solve(N: int, S: "List[str]", P: "List[int]"):
    m = {}
    for i in range(N):
        m[f"{S[i]}-{100-P[i]:03}"] = i+1

    ans = sorted(m.items(), key=lambda x:x[0])

    for v in ans:
        print(v[1])


    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = [str()] * (N)  # type: "List[str]"
    P = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        S[i] = next(tokens)
        P[i] = int(next(tokens))
    solve(N, S, P)

if __name__ == '__main__':
    main()
