#!/usr/bin/env python3
import sys


def solve(d: int, n: int):
    u = 1
    if d == 1:
        u = 100
    if d == 2:
        u = 10000
    ans = u * n
    if n == 100:
        ans += u
    print(ans)

    return


# generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: you use the default template now. you can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    d = int(next(tokens))  # type: int
    n = int(next(tokens))  # type: int
    solve(d, n)

if __name__ == '__main__':
    main()
