#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(S: int):
    s = list(str(S))
    if len(s) == 1:
        if S == 8:
            print(YES)
            return
    elif len(s) == 2:
        if S % 8 == 0 or int(''.join(reversed(s))) % 8 == 0:
            print(YES)
            return
    else:
        a = [0] * 10
        for i in range(len(s)):
            a[int(s[i])] += 1
        for i in range(112, 1000, 8):
            si = list(str(i))
            t = [0] * 10
            for j in range(len(si)):
                t[int(si[j])] += 1
            f = True
            for j in range(len(a)):
                if a[j] < t[j]:
                    f = False
                    break
            if f:
                print(YES)
                return

    print(NO)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = int(next(tokens))  # type: int
    solve(S)

if __name__ == '__main__':
    main()
