#!/usr/bin/env python3
import sys
import math


def get_distance(x1, y1, x2, y2):
    d = math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)
    return d

def solve(X: float, Y: float, R: float):
    l = int(X - R)
    r = int(X + R)
    b = int(Y - R)
    t = int(Y + R)
    ans = 0
    for j in range(b, t+1):
        for i in range(l, r+1):
            if get_distance(X, Y, i, j) <= R:
                ans +=1
    print(ans)

    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    X = float(next(tokens))  # type: float
    Y = float(next(tokens))  # type: float
    R = float(next(tokens))  # type: float
    solve(X, Y, R)

if __name__ == '__main__':
    main()
