#!/usr/bin/env python3
import sys


def solve(N: int, start: int, goal: int, l: "List[int]", r: "List[int]"):
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    start = int(next(tokens))  # type: int
    goal = int(next(tokens))  # type: int
    l = [int()] * (N - 0 + 1)  # type: "List[int]"
    r = [int()] * (N - 0 + 1)  # type: "List[int]"
    for i in range(N - 0 + 1):
        l[i] = int(next(tokens))
        r[i] = int(next(tokens))
    solve(N, start, goal, l, r)

if __name__ == '__main__':
    main()
