#!/usr/bin/env python3
import sys


def solve(N: int):
    s = len(str(N))
    l = [int(s) for s in list(str(N))]
    b = [0] * 3
    for i in l:
        b[i%3] += 1
    a = sum(l) % 3
    if a == 0:
        print(0)
        return
    if a == 1:
        if b[1] > 0 and s != 1:
            print(1)
            return
        if b[2] > 1 and s > 2:
            print(2)
            return
    if a == 2:
        if b[2] > 0 and s != 1:
            print(1)
            return
        if b[1] > 1 and s > 2:
            print(2)
            return
    print(-1)
    return


    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
