#!/usr/bin/env python3
import sys


def solve(K: int, A: int, B: int):
    if A+1 >= B:
        print(1+K)
        return

    ans = 0
    C = K - (A-1)
    c = C // 2
    if C % 2 == 1:
        ans += 1
    ans += (c * (B - A)) + A

    print(ans)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    K = int(next(tokens))  # type: int
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    solve(K, A, B)

if __name__ == '__main__':
    main()
