#!/usr/bin/env python3
import sys


def solve(a, b, c, d):
    x = c -a
    y = d -b
    return print(f"{c-y} {d + x} {a - y} {b + x}")


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    a, b, c, d = map(int, input().split())
    solve(a, b, c, d)

if __name__ == '__main__':
    main()
