#!/usr/bin/env python3
import sys


def solve(N: int, H: "List[int]"):
    ans = 0
    h = H[0]
    m = 0
    for i in range(1, N):
        if h >= H[i]:
            m += 1
        else:
            m = 0
        h = H[i]
        if m >= ans:
            ans = m
    print(ans)


    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    H = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, H)

if __name__ == '__main__':
    main()
