#!/usr/bin/env python3
import sys


def solve(H: int, W: int, S: "List[str]"):
    ans = 0
    for i in range(H):
        for j in range(W):
            if S[i][j] == "#":
                continue
            if i != H-1 and S[i+1][j] == ".":
                ans += 1
            if j != W -1 and S[i][j+1] == ".":
                ans += 1
    print(ans)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(H)]  # type: "List[str]"
    solve(H, W, S)

if __name__ == '__main__':
    main()
