#!/usr/bin/env python3
import sys
import math


def solve(N: int):
    s = set()
    for i in range(1, int(math.sqrt(N) + 2)):
        if N % i == 0:
            s.add(i)
            s.add(N// i)
    for i in sorted(s):
        print(i)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
