#!/usr/bin/env python3
import sys


def solve(A: int, B: int, K: int):
    t = 0
    for i in range(A, (min(B, A+K))):
        print(i)
        t = i

    for i in range(max(t, B-K)+1, B+1):
        print(i)


    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    solve(A, B, K)

if __name__ == '__main__':
    main()
