#!/usr/bin/env python3


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N = int(input())
    A = list(map(int, input().split()))
    acc = [0] * N
    acc[0] = A[0]
    acc_max = [0] * N
    acc_max[0] = A[0]
    acc_max_tmp = A[0]
    for i in range(1, N):
        acc[i] = acc[i-1] + A[i]
        if acc[i] > acc_max_tmp:
            acc_max_tmp = acc[i]
        acc_max[i] = acc_max_tmp
    ans = 0
    dp = [0] * (N + 1)
    for i in range(1, N+1):
        dp[i] = dp[i-1] + acc[i-1]
        max_x = dp[i-1] + acc_max[i-1]
        if max_x > ans:
            ans = max_x
    print(ans)
    return

if __name__ == '__main__':
    main()
