#!/usr/bin/env python3
import sys


def solve(X: int, Y: int, A: int, B: int):
    ans = 0
    while ((X * A )- X) < B and X * A <= Y:
        X *= A
        ans += 1
    D = Y - X -1
    ans += D // B
    print(ans)

    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    X = int(next(tokens))  # type: int
    Y = int(next(tokens))  # type: int
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    solve(X, Y, A, B)

if __name__ == '__main__':
    main()
