#!/usr/bin/env python3
import sys


def solve(S: str):
    for i in range(len(S)-2, 0, -2):
        h = i // 2
        left = S[0:h]
        right = S[h:i]
        if left == right:
            print(i)
            break
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
