#!/usr/bin/env python3

def solve(N: int):
    ans = 0
    for i in range(1, N):
        if N % i == 0:
            ans += (N / i) -1
        else:
            ans += (N // i)
    print(int(ans))

    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N = int(input())
    solve(N)

if __name__ == '__main__':
    main()
