#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(S: str):
    n = S.count("N")
    s = S.count("S")
    w = S.count("W")
    e = S.count("E")

    if n == 0 and s != 0:
        print(NO)
        return
    if s == 0 and n != 0:
        print(NO)
        return
    if w == 0 and e != 0:
        print(NO)
        return
    if e == 0 and w != 0:
        print(NO)
        return
    print(YES)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
