#!/usr/bin/env python3
import sys


def solve(A: int, B: int):
    C = A + B
    if C >= 15 and B >= 8:
        print(1)
    elif C >= 10 and B >= 3:
        print(2)
    elif C >= 3:
        print(3)
    else:
        print(4)

    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    solve(A, B)

if __name__ == '__main__':
    main()
