#!/usr/bin/env python3
import sys
import string

def solve(s: str):
    ans = len(s)
    # アルファベット小文字すべて試す
    for c in string.ascii_lowercase:
        if c in s:
            # 一つ前の位置
            p = -1
            # 右端の位置
            r = 0
            # 一番長い間隔
            d = 0
            for i in range(len(s)):
                if s[i] == c:
                    r = len(s) - i - 1
                    if i != 0:
                        new_d = i - p -1
                        d = max(new_d, d)
                    p = i

            ans = min(ans, max(r, d))
    print(ans)



    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    s = next(tokens)  # type: str
    solve(s)

if __name__ == '__main__':
    main()
