#!/usr/bin/env python3
import sys
import collections


def solve(N: int, S: "List[str]"):
    c = collections.Counter(S).most_common()
    max = c[0][1]
    ans = []
    for key, num in c:
        if max > num:
            break
        ans.append(key)
    ans.sort()
    for s in ans:
        print(s)

    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(N)]  # type: "List[str]"
    solve(N, S)

if __name__ == '__main__':
    main()
