#!/usr/bin/env python3
import sys

YES = "YES"  # type: str
NO = "NO"  # type: str


def solve(S: str):
    o = "keyence"
    a = 0
    for i in range(len(o)):
        if S[i] == o[i]:
            a += 1
        else:
            break
    if a == len(o):
        print(YES)
        return
    if S[-(len(o)-a):] == o[-(len(o)-a):]:
        print(YES)
        return
    if S[-len(o)] == o:
        print(YES)
        return
    print(NO)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
