#!/usr/bin/env python3


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    S = input()
    h = len(S)
    ans = 0
    for i in range(len(S)):
        l = i
        r = h - i -1
        if S[i] == 'U':
            ans += (2 * l) + r
        else:
            ans += (2 * r) + l
    print(ans)

if __name__ == '__main__':
    main()
