#!/usr/bin/env python3


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N = int(input())
    A = list(map(int,input().split()))
    r = 2 ** N // 2
    a = max(A[:r])
    b = max(A[r:])
    if a > b:
        print(A.index(b)+1)
    else:
        print(A.index(a)+1)


if __name__ == '__main__':
    main()
