#!/usr/bin/env python3
import sys


def solve(N: int, s: "List[int]"):
    total = sum(s)
    if total % 10 != 0:
        print(total)
        return
    m = float('inf')
    for i in s:
        if i % 10 != 0:
            m = min(i,m)
    if m == float('inf'):
        print(0)
        return
    print(total-m)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    s = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, s)

if __name__ == '__main__':
    main()
