#!/usr/bin/env python3
import sys


def solve(S: str):
    b = S[0]
    ans = 1
    t = ""
    for c in S[1:]:
        t += c
        if t != b:
            ans += 1
            b = t
            t = ""
        else:
            t = c
    print(ans)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
