#!/usr/bin/env python3
import sys

def solve(N: int):
    s = set()

    for i in range(2,N+1):
        j = 2
        while True:
            t = i ** j
            # print(t)
            if t <= N:
                s.add(t)
            if t >= N:
                break
            j += 1
        if j == 2:
            break
    # print(s)
    print(N - len(s))
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
