#!/usr/bin/env python3
import sys


def solve(X: int):
    n = X % 100
    c = X // 100
    t = n // 5
    if n % 5 != 0:
        t += 1
    if c < t:
        print(0)
        return
    print(1)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    X = int(next(tokens))  # type: int
    solve(X)

if __name__ == '__main__':
    main()
