#!/usr/bin/env python3
import sys


def solve(N: int, K: int):
    for i in range(K):
        s = str(N)
        g1 = ''.join(list(sorted(s, reverse=True)))
        g2 = ''.join(list(sorted(s)))
        N = int(g1) - int(g2)
    print(N)


    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    solve(N, K)

if __name__ == '__main__':
    main()
