#!/usr/bin/env python3


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    T=int(input())
    for i in range(T):
        L, R = map(int, input().split())
        a = R - L
        if a < L:
            print(0)
            continue
        b = a - (L -1)
        c = (b * (b+1)) //2
        print(c)



if __name__ == '__main__':
    main()
