#!/usr/bin/env python3
import sys
import math


def solve(A: int, B: int, W: int):
    w = W * 1000

    max = 0
    min = 0

    c = w // B
    d = c * B
    # print(c, d)
    if d == w:
        min = c
    else:
        min = c + 1

    e = w // A
    f = e * A
    # print(e, f, w- f, (w-f)/e)
    if (w-f)/e > B- A:
        print("UNSATISFIABLE")
    else:
        print(min, e)

    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    solve(A, B, W)

if __name__ == '__main__':
    main()
