#!/usr/bin/env python3
import sys


def solve(A: int, B: int, C: int, D: int):
    A = A -1

    # 最小公倍数を求めるために、最大公約数をもとめる
    g = 0
    b = max(C, D)
    s = min(C, D)
    while True:
        r = b % s
        if r != 0:
            b = s
            s = r
        else:
            g = s
            break

    # 最大公約数を使って最大公倍数をもとめる
    e = (C * D) // g

    b = B
    a = A
    b -= (B // C)
    b -= (B // D)
    b += (B // e)
    a -= (A // C)
    a -= (A // D)
    a += (A // e)

    print(b-a)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    C = int(next(tokens))  # type: int
    D = int(next(tokens))  # type: int
    solve(A, B, C, D)

if __name__ == '__main__':
    main()
