#!/usr/bin/env python3
import sys


def solve(S: str):
    oddWhite = 0
    oddBlack = 0
    evenWhite = 0
    evenBlack = 0
    for i in range(0, len(S)):
        if i % 2 == 0:
            if S[i] == '1':
                oddWhite += 1
            else:
                oddBlack += 1
        elif S[i] == '1':
            evenWhite += 1
        else:
            evenBlack += 1
    ans = min(oddBlack + evenWhite, evenBlack+ oddWhite)
    print(ans)

    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
