#!/usr/bin/env python3
import sys


def solve(N: int, S: "List[str]"):
    t = 0
    f = 0
    if S[0] == "AND":
        t = 1
        f = 3
    else:
        t = 3
        f = 1
    for i in range(1, N):
        if S[i] == "OR":
            t = t*2 + f
        else:
            f = f * 2 + t
    print(t)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(N)]  # type: "List[str]"
    solve(N, S)

if __name__ == '__main__':
    main()
