#!/usr/bin/env python3
import sys


def solve(A: int, B: int):
    ans = 0
    C = abs(A-B)
    ans += C // 10
    D = C % 10
    if D == 5 or D == 1:
        ans += 1
    elif D == 9 or D == 6 or D == 4 or D == 2:
        ans += 2
    elif D == 8 or D == 7 or D == 3:
        ans += 3
    print(ans)

    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    solve(A, B)

if __name__ == '__main__':
    main()
