#!/usr/bin/env python3
import sys


def solve(N: int, A: "List[int]"):
    ans = 0
    left = A[0]
    right = A[-1]
    li = 1
    ri = -2
    for i in range(N-2):
        if left > right:
            right += A[ri]
            ri -= 1
        else:
            left += A[li]
            li += 1
    print(abs(left-right))

    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, A)

if __name__ == '__main__':
    main()
