#!/usr/bin/env python3
import sys
import math


def solve(N: int):
    n = str(N)
    ans = 0

    if len(n) <= 3:
        print(0)
        return

    for i in range(3, len(n)):
        j = i + 1
        r  = math.ceil(j / 3) - 1
        if i == len(n) -1 :
            k = N - int(''.join([str(9)] * i ))
            # print(k, r)
            ans += k * r
            break
        else:
            c  = 10 ** i * 9
            # print(j, r, c)
            ans += c * r

    print(ans)



    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
