#!/usr/bin/env python3


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    H, W = map(int, input().split())
    f = [[0] * W for i in range(H)]
    for i in range(H):
        f[i] = list(input())

    for i in range(H):
        flg = True
        for j in range(W):
            if f[i][j] == '#':
                flg = False
                break
        if flg:
            for j in range(W):
                 f[i][j] = ''

    for j in range(W):
        flg = True
        for i in range(H):
            if f[i][j] == '#':
                flg = False
                break
        if flg:
            for i in range(H):
                 f[i][j] = ''

    for i in range(H):
        flg = False
        for j in range(W):
            if f[i][j] != '' :
                flg = True
                print(f[i][j], end="")
        if flg:
            print()



if __name__ == '__main__':
    main()
